project:
  type: manuscript

manuscript:
  article: index.qmd

date: today
date-format: long

format:
  html: default
  pdf: 
    fontsize: 12pt
    mainfont: "CMU Serif"
    documentclass: article
    classoption: usletter
    toc: false
    colorlinks: true
    urlcolor: "PaleGreen4!75!black"
    latex-auto-install: false
    geometry: 
      - margin=1in
      - nohead
      - nomarginpar


execute:
  freeze: true



