project:
  type: manuscript

manuscript:
  article: index.qmd

date: today
date-format: long

csl: astronomy-and-computing.csl

format:
  html: 
    css: styles.css
    title-block-banner: "#E6E6FA"
    include-in-header: 
      text: <meta name="theme-color" content="#E6E6FA"/>

  arxiv-pdf: 
    fontsize: 12pt
    colorlinks: true
    urlcolor: "PaleGreen4!75!black"

execute:
  cache: true
  echo: false
  output: true

jupyter: julia-1.9
