project:
  type: manuscript

manuscript:
  article: index.qmd

date: today
date-format: long

csl: astronomy-and-computing.csl

format:
  html: 
    css: styles.css
    title-block-banner: "#E6E6FA"
    include-in-header: 
      text: <meta name="theme-color" content="#E6E6FA"/>

  markdown: 
    output-file: paper

  arxiv-pdf: 
    output-file: preprint
    fontsize: 12pt
    colorlinks: true
    urlcolor: "PaleGreen4!75!black"
